#!/bin/bash

dir=$1 # | sed 's/\.\([^$]\)/-\1/g'

if [ "$dir" = "" ];then
    echo "Please, inform the directory param."
    exit 1
fi

if [ ! -d "$dir" ]; then
    echo "Please, inform a valid directory."
    exit 1
fi

cpright=$(<$2)
#echo "$cpright"

shopt -s globstar

for file in $dir/**
do
	if [[ ${file: -5} == ".java" ]]
	then
      	    sed -i ' 1 i\/* \n *Copyright (c) 2015 Samsung Electronics Co., Ltd. \n * All rights reserved. \n * \n * This software is a confidential and proprietary information of Samsung \n * Electronics, Inc. ("Confidential Information").  You shall not disclose such \n * Confidential Information and shall use it only in accordance with the terms \n * of the license agreement you entered into with Samsung Electronics. \n */ \n'  $file
	    #sed  '${s/$/'"$cpright"'/}' $file
	    echo "File updated:" $file
  	fi
done 
